/**
 * scripts/cleanup-e2e.js
 *
 * Remove all test data created by the E2E test suite.
 * Test wallets always start with "0xe2e" (lowercase — SQLite stores them as-is,
 * so match both cases with LIKE using lower()).
 *
 * Run manually:  node scripts/cleanup-e2e.js
 * Or via npm:    npm run db:cleanup-e2e
 */

'use strict';

require('dotenv').config();
const Database = require('better-sqlite3');
const config = require('../src/config');

const db = new Database(config.dbPath);

const PATTERN = '0xe2e%';

function deleteWhere(table, column, pattern) {
  const result = db
    .prepare(`DELETE FROM ${table} WHERE lower(${column}) LIKE lower(?)`)
    .run(pattern);
  if (result.changes > 0) {
    console.log(`  Deleted ${result.changes} row(s) from ${table}`);
  }
  return result.changes;
}

console.log('\nCleaning up E2E test data (wallets matching 0xe2e*)...\n');

let total = 0;

// Stamp-related
total += deleteWhere('stamp_events', 'wallet_address', PATTERN);
total += deleteWhere('stamps', 'wallet_address', PATTERN);
total += deleteWhere('free_stamp_cooldown', 'wallet_address', PATTERN);

// Agent-related
// First get agent IDs so we can clean up dependent tables
const testAgents = db
  .prepare("SELECT id FROM agents WHERE lower(wallet_address) LIKE lower(?)")
  .all(PATTERN);

if (testAgents.length > 0) {
  const agentIds = testAgents.map((a) => a.id);
  const placeholders = agentIds.map(() => '?').join(',');

  const hbDeleted = db
    .prepare(`DELETE FROM heartbeat_log WHERE agent_id IN (${placeholders})`)
    .run(...agentIds);
  if (hbDeleted.changes > 0) {
    console.log(`  Deleted ${hbDeleted.changes} row(s) from heartbeat_log`);
  }

  const endDeleted = db
    .prepare(`DELETE FROM endorsements WHERE agent_id IN (${placeholders})`)
    .run(...agentIds);
  if (endDeleted.changes > 0) {
    console.log(`  Deleted ${endDeleted.changes} row(s) from endorsements`);
  }

  total += hbDeleted.changes + endDeleted.changes;
}

total += deleteWhere('agents', 'wallet_address', PATTERN);
total += deleteWhere('free_registration_cooldown', 'wallet_address', PATTERN);

// Wallet links
total += deleteWhere('wallet_links', 'primary_wallet', PATTERN);
// Also clean up any links where the test wallet was the linked wallet
const linkedCount = db
  .prepare(
    "DELETE FROM wallet_links WHERE lower(linked_wallet) LIKE lower(?)"
  )
  .run(PATTERN);
if (linkedCount.changes > 0) {
  console.log(`  Deleted ${linkedCount.changes} row(s) from wallet_links (linked_wallet)`);
}
total += linkedCount.changes;

// Transactions generated by E2E wallets
total += deleteWhere('transactions', 'wallet_address', PATTERN);

// Event log entries for E2E wallets
total += deleteWhere('event_log', 'wallet_address', PATTERN);

// Webhooks
total += deleteWhere('webhooks', 'wallet_address', PATTERN);

console.log(`\nDone. Removed ${total} total row(s).\n`);

db.close();
